'use strict';
/* GENERATED by tools/doctrine-past.js; do not edit by hand (#4890). Every working-rules block engine/defaults.js has
   produced in git history (released or not), by fingerprint: `length` in JavaScript string units from the block's
   first line, and the sha256 of exactly those characters. doctrine.planFor uses it to tell an unedited copy from one
   a person changed. */
module.exports = [
  { version: 21, length: 21919, sha256: '8f049db34502268da4258dda6c2e242f8c13373b38f1e43800091e091c62aa5b' },
  { version: 21, length: 21916, sha256: 'ff04f9d92e6c5917a67fff81781e8775d809467e312d8bb3f00aa04f5fed0e53' },
  { version: 20, length: 22046, sha256: '6f0045422d9692730773d914297bb6b6eb219fc7a193ddf27db2698f7a99bf21' },
  { version: 19, length: 22328, sha256: '6a3604bd76d0099f4598f4313544837e137fb72fd33d135202daeb20c7eea2a0' },
  { version: 19, length: 22270, sha256: '573e956577430b3f30eddc570d53f811246706c0befcac01ce3508d5bab7c985' },
  { version: 19, length: 22199, sha256: '2c9b55c00161dfb3d74b7cd719760369ec0857f85e236f07a2ba93bc610a5113' },
  { version: 18, length: 21400, sha256: '06878b58888750af4928098ab3de6a8f661c75b5e72ae03b38a383da397a0e34' },
  { version: 17, length: 21127, sha256: 'f9535c046e6d92c57b90685204c7d035027ef096f94e815ce408ae353b8477c8' },
  { version: 16, length: 20519, sha256: 'a5a8b014f0bf207d23084aeca9a53f123e85d93c8f1464978610f0dee8d158ab' },
  { version: 15, length: 18939, sha256: '48ac419c5b7aadf753691bd126cc1861273da7e118d96524dab2f4e27d93666d' },
  { version: 14, length: 16969, sha256: '0310a25a5164964251b08719778ca724b3988254c480eccacee1f292271b2030' },
  { version: 13, length: 16429, sha256: 'a1369c0c9db5dd062838ea3444e5e829258f65c28c5e971bd925ed04d3df713e' },
  { version: 13, length: 16277, sha256: 'dae349489371dc02cdc13f0abeb41fd6a45a0cf1ccd279d06ee49b747d92c807' },
  { version: 12, length: 15602, sha256: '0a27542356985c22b7df4108660557c2e3948b1e02f06e97a01e4301ceea5c13' },
  { version: 11, length: 15168, sha256: '7264c62fb8605bcc720c6983cfb69766943312e066a634940200bb97639ab091' },
  { version: 10, length: 14662, sha256: 'd6043a51e7c6b5b73a00ff1ab418f1638a01bd7bb990bb1faea7194ddceef257' },
  { version: 10, length: 14642, sha256: 'fe5a6bc6047f595baac728c8e018f3d4a864098b2313528048abc8c8d888ac57' },
  { version: 10, length: 14552, sha256: 'c35c52f07e0056e9bda61335c50ceaf32f6e18e0eb1c276258edd85f6b862f8e' },
  { version: 10, length: 14482, sha256: '78cab3ec8d8560dbf105b3a780664459dfc66603517f50594a115784eedd2217' },
  { version: 9, length: 12950, sha256: '55166f13216cf92a04b8d49dd97f613f3970009f498dbeb0b69717dd97419089' },
  { version: 8, length: 12665, sha256: '8e5de18bfdef3631cba126844ad8a8da8e544d8416a95309ec6cf524759b6a5a' },
  { version: 7, length: 11799, sha256: '92cbc9e7da9b313b2d5b17734a27b19872bd8f100d1132cd5b7a39980089fa69' },
  { version: 6, length: 10637, sha256: '6b112e796679a0288ceb77c78a5b0bd1323a52b0c68ff1f9122701a81a41856e' },
  { version: 5, length: 10272, sha256: 'c424dc531fca1b91335357f00207ce1441e4ae85e863998365d61ca543c65039' },
  { version: 4, length: 7411, sha256: '3ea7865f183bff5bb2395e22ee65ba60b2695257fbe1b252d4b3c91509c23ff1' },
  { version: 3, length: 6248, sha256: '78435e4dc9286b307f0206c75b995c884186e8a5e741af42fd464839c999fe61' },
  { version: null, length: 5761, sha256: '118080f63230d3d0379c5343cccd5a34e1f9ed81023b035d9c402d758407622d' },
];
