'use strict';
/**
 * #3380 TRUE END-TO-END: a codex (OpenAI) agent, born through the REAL create flow
 * with its REAL generated brief, given a PLAIN operator message, actually
 * (1) enumerates LIVE and (2) POSTS A REPLY THAT LANDS ON THE BOARD.
 *
 * 🛑 WHY THIS REPLACES THE HAND-WRITTEN-BRIEF VERSION, AND WHAT THAT ONE COULD NOT
 * SEE (#3380 round 3). The prior version of this file wrote a TIGHT hand-authored
 * AGENTS.md that literally said `run kosmos reply "CODEX_E2E_REPLY_OK"` and then
 * called `handle.send()` DIRECTLY. So it proved the reply PLUMBING works when the
 * brief spells out the exact command -- but it never tested the two layers that
 * actually decide whether a real agent answers:
 *   1. Does the REAL Kosmos-generated brief (roles + the operating doctrine +
 *      the connections block, ~22KB) -- given a PLAIN "hi", not an explicit
 *      instruction -- make codex run `kosmos reply` at all? (It does: the doctrine's
 *      "Answering the person who messaged you" section teaches exactly that, and
 *      codex 0.149.1 obeys it. A test that hands codex the command cannot see this.)
 *   2. Is the agent ENUMERATED LIVE by `win32codexlive`? A codex agent's card, its
 *      state, AND message DELIVERY are all gated on it appearing in the roster
 *      (chat.deliver -> addressable requires a roster card BEFORE the channel). The
 *      prior test bypassed the roster entirely by calling handle.send, so an agent
 *      that never enumerated live would still have "passed".
 *
 * 🔑 SO THIS FAKES NOTHING ON THE PATH UNDER TEST. The brief is generated by the
 * real `create.createAgent({ provider: 'openai' })` (its AGENTS.md, in its worker
 * folder). The turn runs under the real `win32launch.childEnv(..., 'codex')` (where
 * #3420's ExecutionPolicy fix lives), through the real `win32codex.runCodexTurn`,
 * driven by the real `win32codexsup.superviseCodexStreaming` with the real
 * `win32streamstate.publisher` (the production presence/state writer). The message
 * is the envelope `chat.deliver` builds, carrying a PLAIN "hi". The assertions are
 * (a) `win32codexlive.liveSessions()` lists this agent, and (b) the reply text lands
 * in the board's DIRECT thread for it, attributed to it.
 *
 * 🛑 WIN32-GATED AND ACCOUNT-GATED: it spawns the real codex binary and makes real
 * API calls, so it SKIPS off-win32 and skips when the binary or the signed-in test
 * home is absent. It touches NEITHER the operator's store nor the live board:
 * everything runs against a throwaway sandbox data dir and a board on port 0.
 *
 *   node --test engine/win32codexreply.e2e.test.js
 */
const os = require('node:os');
const path = require('node:path');
const fs = require('node:fs');

// ── Sandbox EVERYTHING before requiring anything that freezes store.ROOT ──────
const SANDBOX = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'codex-e2e-')));
process.env.AGENT_WORKFORCE_DATA = path.join(SANDBOX, 'data');
process.env.AGENT_WORKFORCE_WORKERS = path.join(SANDBOX, 'workers');
process.env.AGENT_WORKFORCE_LAUNCH = path.join(SANDBOX, 'launch');
process.env.AGENT_WORKFORCE_PROJECTS = path.join(SANDBOX, 'projects');
process.env.AGENT_WORKFORCE_HOME = SANDBOX;
process.env.AGENT_WORKFORCE_CLAUDE_CONFIG = path.join(SANDBOX, 'claude.json');
process.env.AGENT_WORKFORCE_TMUX_BIN = path.join(__dirname, '..', 'test-support', 'fake-tmux.sh');
process.env.AGENT_WORKFORCE_FAKE_PANES = path.join(SANDBOX, 'panes.txt');
process.env.KOSMOS_NO_LEGACY_MIGRATION = '1';

const test = require('node:test');
const assert = require('node:assert/strict');

const { start, server, boardAuthState } = require('../server');
const chat = require('./chat');
const liveness = require('./liveness');
const win32launch = require('./win32launch');
const win32streamstate = require('./win32streamstate');
const win32codexlive = require('./win32codexlive');
const win32sessions = require('./win32sessions');
const create = require('./create');
const job = require('./win32job');
const { superviseCodexStreaming } = require('./win32codexsup');
const fleet = require('../test-support/fleet');

const CODEX_BIN = 'C:/Users/joshu/.local/share/kosmos/runners/openai/pkg/vendor/x86_64-pc-windows-msvc/bin/codex.exe';
const CODEX_HOME = 'C:/Users/joshu/work/codex-test-home';

const ready = process.platform === 'win32'
  && fs.existsSync(CODEX_BIN)
  && fs.existsSync(path.join(CODEX_HOME, 'auth.json'));

const AGENT = 'codexe2e';

test('#3380 a codex agent BORN FROM ITS REAL BRIEF, given a plain message, enumerates live and its reply LANDS', { skip: !ready, timeout: 240000 }, async () => {
  // 1. The real board, on an ephemeral port, fully sandboxed (enforcement OFF).
  await start(0);
  const port = server.address().port;
  assert.equal(boardAuthState.on, false, 'a fully-sandboxed board must not enforce');

  // 2. Born through the REAL create flow, so its AGENTS.md is the REAL generated
  //    brief. `status.paneRoster` and win32job are stubbed so the creation completes
  //    on this box without touching real Scheduled Tasks (the sibling create tests'
  //    seam); the brief itself is untouched, written by create.js.
  require('./status').paneRoster = () => [];
  let seq = 0;
  job.setAnchorer(() => ({ ok: true, node: 'C:\\Anchor\\node.exe', boot: 'C:\\Anchor\\boot.js' }));
  job.setRunner((args) => {
    // `/Run` is where the supervisor writes its ownership row; the fixture writes one
    // so create's awaitSession sees the agent appear (create completes, no rollback).
    if (args && args[0] === '/Run') win32sessions.record('born-' + (++seq) + '-0000', { name: AGENT, runner: 'codex' });
    if (args && args[0] === '/Query') return { ok: false, out: 'ERROR: The system cannot find the file specified.' };
    return { ok: true, out: '' };
  });
  const born = create.createAgent({ name: AGENT, role: 'ea', provider: 'openai', codexBin: CODEX_BIN });
  assert.equal(born.outcome, create.OUTCOME.CREATED, 'the codex agent was created (' + (born.because || '') + ')');
  const cwd = create.workerDir(AGENT);
  const brief = fs.readFileSync(path.join(cwd, 'AGENTS.md'), 'utf8');
  assert.ok(brief.includes('kosmos reply'), 'the REAL brief teaches kosmos reply');
  assert.ok(brief.includes('How you work, whatever the job'), 'the REAL brief carries the operating doctrine');

  // 3. The zip-shaped bundle the agent's `kosmos` command resolves through:
  //    <bundle>/bin/{kosmos.ps1,kosmos-cli.js}, <bundle>/runtime/node.exe,
  //    <bundle>/app/engine (kosmos-cli.js's engineDir). Junctions need no admin.
  const tools = path.join(__dirname, '..', 'tools', 'windows');
  const bundle = path.join(SANDBOX, 'bundle');
  const bin = path.join(bundle, 'bin');
  fs.mkdirSync(bin, { recursive: true });
  fs.copyFileSync(path.join(tools, 'kosmos.ps1'), path.join(bin, 'kosmos.ps1'));
  fs.copyFileSync(path.join(tools, 'kosmos-cli.js'), path.join(bin, 'kosmos-cli.js'));
  fs.symlinkSync(path.dirname(process.execPath), path.join(bundle, 'runtime'), 'junction');
  fs.mkdirSync(path.join(bundle, 'app'), { recursive: true });
  fs.symlinkSync(__dirname, path.join(bundle, 'app', 'engine'), 'junction');

  // 4. The account and the board port ride in this process's env, so the REAL
  //    childEnv the supervisor builds carries them into the turn -- CODEX_HOME picks
  //    the signed-in account, KOSMOS_PORT points the agent's kosmos CLI at THIS board.
  process.env.CODEX_HOME = CODEX_HOME;
  process.env.KOSMOS_PORT = String(port);

  // 5. /api/reply attributes off the roster (the standard reply-test seam): a
  //    one-agent fake fleet whose name matches the token the supervisor mints.
  fleet.install([fleet.agent(AGENT, { state: 'idle' })]);
  liveness.seen(AGENT);

  const events = [];
  // The PRODUCTION presence/state publisher -- the same one main() wires. Its
  // stream.started() stamp is what win32codexlive reads back to enumerate this agent.
  const publisher = win32streamstate.publisher(AGENT, {
    onProblem: (why) => events.push('state-problem -- ' + why),
  });
  const h = superviseCodexStreaming(
    { name: AGENT, cwd, runner: 'codex', claudeBin: CODEX_BIN },
    {
      bin: CODEX_BIN,
      cliDir: bin,               // the bundle's bin -> real kosmos.ps1 on the agent's PATH
      stream: publisher,         // production presence + working/idle
      // NO `env`, `runTurn`, `prepare` or `sessions` override: the real childEnv
      // (where #3420's fix lives), the real codex driver, the real session mint.
      onEvent: (e) => events.push(e.action + (e.because ? ' -- ' + e.because : '')),
    },
  );
  const beat = setInterval(() => { try { liveness.seen(AGENT); } catch { /* best effort */ } }, 5000);

  try {
    // (a) THE LIVENESS ASSERTION the prior test never made: the agent is enumerated
    //     live by the codex live source, which is what gives it a roster card and
    //     makes it deliverable. Without this, chat.deliver drops the message before
    //     it ever reaches the agent.
    const live = win32codexlive.liveSessions();
    const mine = live.find((r) => r.name === AGENT);
    assert.ok(mine, 'the codex agent is enumerated LIVE by win32codexlive (events: ' + JSON.stringify(events) + ')');
    assert.equal(mine.runner, 'codex');

    // The wire a real operator message arrives as: the envelope chat.deliver builds,
    // naming the reply command, then a PLAIN message -- NOT an explicit instruction
    // to run kosmos reply with a marker.
    const wire = '[message from your operator \u00b7 to answer, run: kosmos reply] hi';
    await new Promise((res) => h.send(wire, res));

    // (b) THE REPLY ASSERTION: some reply text landed in the board's DIRECT thread
    //     for this agent -- written by the real /api/reply route, reached by the
    //     agent's own kosmos CLI over HTTP, because the REAL brief made codex run it.
    const landed = await waitFor(() => {
      let msgs = [];
      try { msgs = chat.readThread(chat.DIRECT, AGENT).messages || []; } catch { msgs = []; }
      return msgs.find((m) => typeof m.text === 'string' && m.text.trim().length > 0);
    }, 200000);

    assert.ok(landed, 'a reply from the codex agent reached the board (events: ' + JSON.stringify(events) + ')');
    assert.equal(landed.from, AGENT, 'the reply is attributed to this agent, not a bare pane');
  } finally {
    clearInterval(beat);
    h.stop();
    try { fleet.restore(); } catch { /* best effort */ }
    try { job.setRunner(null); } catch { /* best effort */ }
    try { job.setAnchorer(null); } catch { /* best effort */ }
    try { create.setRunner(null); } catch { /* best effort */ }
    await new Promise((res) => server.close(res));
    try { fs.rmSync(SANDBOX, { recursive: true, force: true }); } catch { /* best effort */ }
  }
});

function waitFor(pred, ms) {
  const deadline = Date.now() + ms;
  return new Promise((resolve) => {
    const tick = () => {
      let v = false;
      try { v = pred(); } catch { v = false; }
      if (v) return resolve(v);
      if (Date.now() > deadline) return resolve(null);
      setTimeout(tick, 500);
    };
    tick();
  });
}
