#!/usr/bin/env node
'use strict';
/*
 * Regenerates engine/doctrine-past.js (#4890): the fingerprint of every working-rules block Kosmos has ever
 * written into an agent's instructions, so doctrine.planFor can recognise an unedited plain copy and offer the
 * current rules in its place. Run it after changing BLOCK in engine/defaults.js (doctrine.test.js reds until you
 * do):
 *
 *   node tools/doctrine-past.js
 *
 * It reads engine/defaults.js at every commit that touched it, plus the working copy, and needs the full git
 * history (a shallow clone lists fewer versions; the test catches a table that lost the current block, not one
 * that lost an old one, so run this in a full clone).
 */
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'engine', 'doctrine-past.js');
const git = (...args) => execFileSync('git', ['-C', ROOT, ...args], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'doctrine-past-'));
try {
  const shas = git('log', '--format=%H', '--', 'engine/defaults.js').trim().split('\n').filter(Boolean);
  const sources = shas.map((h) => ({ from: h.slice(0, 9), text: git('show', `${h}:engine/defaults.js`) }));
  sources.unshift({ from: 'working copy', text: fs.readFileSync(path.join(ROOT, 'engine', 'defaults.js'), 'utf8') });
  const seen = new Map();
  sources.forEach((src, i) => {
    const file = path.join(tmp, `d${i}.js`);
    fs.writeFileSync(file, src.text);
    const mod = require(file);
    const block = typeof mod.block === 'function' ? mod.block() : null;
    if (typeof block !== 'string' || !block) return;
    const sha256 = crypto.createHash('sha256').update(block).digest('hex');
    if (!seen.has(sha256)) seen.set(sha256, { version: Number.isFinite(mod.DOCTRINE_VERSION) ? mod.DOCTRINE_VERSION : null, length: block.length, sha256 });
  });
  const rows = [...seen.values()].sort((a, b) => (b.version || 0) - (a.version || 0) || b.length - a.length);
  const body = [
    "'use strict';",
    '/* GENERATED by tools/doctrine-past.js; do not edit by hand (#4890). Every working-rules block Kosmos has written',
    '   into an agent, by fingerprint: `length` in JavaScript string units from the block\'s first line, and the sha256 of',
    '   exactly those characters. doctrine.planFor uses it to tell an unedited plain copy from one a person changed. */',
    'module.exports = [',
    ...rows.map((r) => `  { version: ${r.version === null ? 'null' : r.version}, length: ${r.length}, sha256: '${r.sha256}' },`),
    '];',
    '',
  ].join('\n');
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${rows.length} blocks to ${path.relative(ROOT, OUT)}`);
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
