#!/usr/bin/env node
'use strict';
/*
 * Regenerates engine/doctrine-past.js (#4890): the fingerprint of every working-rules block Kosmos has ever
 * written into an agent's instructions, so doctrine.planFor can recognise an unedited plain copy and offer the
 * current rules in its place. Run it after changing BLOCK in engine/defaults.js (engine/doctrine-4890.test.js
 * reds until you do):
 *
 *   node tools/doctrine-past.js
 *
 * It reads engine/defaults.js at every commit that touched it, plus the working copy, and needs the full git
 * history (a shallow clone lists fewer versions, so run this in a full clone). engine/defaults.test.js fails when
 * any released version (each fingerprint it pins) has no row, or when the current block has none.
 * A commit on a branch that never shipped is in the table too, labelled with whatever DOCTRINE_VERSION it had then;
 * no agent holds such a block, so its row matches nothing.
 */
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'engine', 'doctrine-past.js');
const git = (...args) => execFileSync('git', ['-C', ROOT, ...args], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'doctrine-past-'));
try {
  // --full-history: every side of a merge, not git's simplified one, so no block depends on how a branch merged (review 20).
  const shas = git('log', '--full-history', '--format=%H', '--', 'engine/defaults.js').trim().split('\n').filter(Boolean);
  const sources = shas.map((h) => ({ from: h.slice(0, 9), text: git('show', `${h}:engine/defaults.js`) }));
  sources.unshift({ from: 'working copy', text: fs.readFileSync(path.join(ROOT, 'engine', 'defaults.js'), 'utf8') });
  const seen = new Map();
  const texts = new Map();
  const sectionShas = new Set();
  let skipped = 0;
  sources.forEach((src, i) => {
    const file = path.join(tmp, `d${i}.js`);
    fs.writeFileSync(file, src.text);
    let mod;
    try { mod = require(file); } catch (err) { console.warn(`skipped ${src.from}: ${err.message}`); skipped += 1; return; }
    const block = typeof mod.block === 'function' ? mod.block() : null;
    if (typeof block !== 'string' || !block) return;
    const sha256 = crypto.createHash('sha256').update(block).digest('hex');
    if (!seen.has(sha256)) seen.set(sha256, { version: Number.isFinite(mod.DOCTRINE_VERSION) ? mod.DOCTRINE_VERSION : null, length: block.length, sha256 });
    texts.set(sha256, block);
    // Each section, split as defaults.sections() splits, so a span holding only some sections can be recognised.
    block.split('\n### ').forEach((p, j) => sectionShas.add(crypto.createHash('sha256').update(j === 0 ? p : '### ' + p).digest('hex')));
  });
  if (skipped) throw new Error(`${skipped} version(s) of engine/defaults.js could not be loaded; the table would miss them`);
  /* doctrine.pastBlockIn tells an earlier block from a longer one it is a prefix of by what follows it: a longer
     block must go on with a new `###` section. An earlier block that a later one extends INSIDE its last section
     cannot be told apart, so it is left out: agents holding it keep the missing-headings rule (never a wrong cut). */
  for (const [ka, a] of texts) {
    for (const [kb, b] of texts) {
      if (ka !== kb && b.length > a.length && b.startsWith(a) && b[a.length] === '\n'
        && !/^(?:[ \t]*\r?\n)*### /.test(b.slice(a.length + 1))) {
        console.warn(`left out the ${a.length}-character block: a later one extends it inside its last section`);
        seen.delete(ka);
      }
    }
  }
  const rows = [...seen.values()].sort((a, b) => (b.version || 0) - (a.version || 0) || b.length - a.length);
  const body = [
    "'use strict';",
    '/* GENERATED by tools/doctrine-past.js; do not edit by hand (#4890). Every working-rules block engine/defaults.js has',
    '   produced in git history (released or not), by fingerprint: `length` in JavaScript string units from the block\'s',
    '   first line, and the sha256 of exactly those characters. doctrine.planFor uses it to tell an unedited copy from one',
    '   a person changed. `sections` holds the sha256 of every section of every one of them, for a span holding some. */',
    'const blocks = [',
    ...rows.map((r) => `  { version: ${r.version === null ? 'null' : r.version}, length: ${r.length}, sha256: '${r.sha256}' },`),
    '];',
    'blocks.sections = [',
    ...[...sectionShas].sort().map((h) => `  '${h}',`),
    '];',
    'module.exports = blocks;',
    '',
  ].join('\n');
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${rows.length} blocks and ${sectionShas.size} sections to ${path.relative(ROOT, OUT)}`);
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
