'use strict';
/**
 * Build engine/catalogue-roles.js and engine/catalogue-teams.js from the two source modules
 * beside this file (#4555).
 *
 *     node tools/catalogue/build.js            (write)
 *     node tools/catalogue/build.js --check    (exit 1 if a generated file is stale)
 *
 * Each generated file is `module.exports = <JSON>;`: JSON so any tool can read it, a .js module
 * because the Mac and Windows builds ship engine/*.js and nothing else (build-kosmos-bundle.sh,
 * build-kosmos-windows.sh), so data in a .json file would be missing from every served build.
 *
 * It checks what it can before writing; engine/catalogue.test.js checks the same things again
 * against what the product actually reads, and calls build() to prove the files are current.
 */
const fs = require('node:fs');
const path = require('node:path');

const HERE = __dirname;
const OUT = path.join(HERE, '..', '..', 'engine');
const NOTE = 'GENERATED by tools/catalogue/build.js from tools/catalogue/*-source.js. Edit the source, not this file.';

// Words kept in capitals inside a sentence ("a PR specialist", "an HR policy writer").
const ACRONYMS = new Set(['CRM', 'HR', 'PR', 'QA', 'SEO', 'UX']);
// The house rule's spellings of the em dash: the character, the named and numeric entities
// (hex in either case), and the two source escapes. Written as escapes here, so this file has none.
const EM_DASHES = ['\u2014', '&mdash;', '&#8212;', '&#x2014;', '&#X2014;', '\\u2014', '\\u{2014}'];

function lowerLabel(label) {
  return label.split(/\s+/).map((w) => (ACRONYMS.has(w) ? w : w.toLowerCase())).join(' ');
}

/** "an" before a vowel sound: a vowel letter, or an acronym whose first letter's name starts
 *  with one (HR is "aitch-ar"). UX starts "you", so it takes "a". */
function articleFor(phrase) {
  const first = phrase.split(/\s+/)[0];
  if (ACRONYMS.has(first)) return 'AEFHILMNORSX'.includes(first[0]) ? 'an' : 'a';
  return 'aeiou'.includes(first[0].toLowerCase()) ? 'an' : 'a';
}

/** Greedy wrap at 76 columns, breaking only at spaces. */
function wrap(text, first = '', rest = '') {
  const out = [];
  let line = first;
  let empty = true;
  for (const word of String(text).split(/\s+/).filter(Boolean)) {
    const next = empty ? line + word : line + ' ' + word;
    if (!empty && next.length > 76) { out.push(line); line = rest + word; } else line = next;
    empty = false;
  }
  out.push(line);
  return out;
}

function sentences(text) {
  return String(text).split(/[.!?](?:\s|$)/).filter((s) => s.trim()).length;
}

function instructions(r) {
  const noun = lowerLabel(r.label);
  const lines = [`You are **{{NAME}}**, ${articleFor(noun)} ${noun}.`, ''];
  lines.push(...wrap(r.desc), '', '## Who you are', '', ...wrap(r.who), '', '## How you work', '');
  for (const b of r.how) lines.push(...wrap(b, '- ', '  '));
  return lines;
}

/** Any of the five spellings anywhere in the value. JSON.stringify keeps the character itself and
 *  writes a typed backslash-u escape as \\u2014, which still contains the escape spelling. */
function emDashIn(value) {
  const blob = JSON.stringify(value);
  // Plus zero-padded numeric entities, the way tools/check-post-body.js matches them.
  return EM_DASHES.some((s) => blob.includes(s)) || /&#0*8212;|&#x0*2014;/i.test(blob);
}

/**
 * Compose both generated files from the sources.
 * @param {{rolesSource?: object, teamsSource?: object}} [src] sources to use instead of the files
 *   beside this module (a test passes an edited copy)
 * @returns {{files: Object<string,string>, problems: string[]}}
 */
function build(src = {}) {
  const rs = src.rolesSource || require('./roles-source');
  const ts = src.teamsSource || require('./teams-source');
  const problems = [];
  const groups = rs.GROUP_ORDER;
  const roles = [];
  const seen = new Set();
  for (const r of rs.roles) {
    const k = r.key;
    if (seen.has(k)) problems.push('duplicate role key ' + k);
    seen.add(k);
    if (!groups.includes(r.group)) problems.push(`${k}: unknown group ${r.group}`);
    const n = sentences(r.who);
    if (n < 3 || n > 6) problems.push(`${k}: character is ${n} sentences, three to six is the rule`);
    if (!Array.isArray(r.how) || r.how.length !== 3) problems.push(`${k}: How you work needs exactly three bullets`);
    if (!r.first || r.first.length <= 10) problems.push(`${k}: first action too short`);
    const entry = { key: k, group: r.group, label: r.label, blurb: r.blurb, firstAction: r.first };
    if (r.caution) entry.caution = r.caution;
    entry.instructions = instructions(r);
    // The product's wrapper keeps a `code span` on one line; this one does not, so refuse text
    // whose wrap would split one (an odd count of backticks on a line) rather than ship it broken.
    if (entry.instructions.some((l) => (l.match(/`/g) || []).length % 2)) problems.push(`${k}: a code span is split across lines`);
    if (emDashIn(entry)) problems.push(`${k}: em dash`);
    roles.push(entry);
  }
  const teams = [];
  const seenNames = new Map();
  const seenRanks = new Map();
  for (const t of ts.teams) {
    for (const m of t.members) {
      const lower = m.name.toLowerCase();
      if (seenNames.has(lower)) problems.push(`suggested name ${m.name} is used by ${seenNames.get(lower)} and ${t.key}`);
      seenNames.set(lower, t.key);
    }
    if (!['business', 'personal'].includes(t.kind)) problems.push(`${t.key}: kind must be business or personal`);
    if (!Number.isInteger(t.rank) || t.rank < 1) problems.push(`${t.key}: rank must be a whole number from 1`);
    const rk = t.kind + '#' + t.rank;
    if (seenRanks.has(rk)) problems.push(`${seenRanks.get(rk)} and ${t.key} share ${t.kind} rank ${t.rank}`);
    seenRanks.set(rk, t.key);
    const leads = t.members.filter((m) => m.slot === 'lead').length;
    if (leads !== 1) problems.push(`${t.key}: needs exactly one lead slot, has ${leads}`);
    const reports = t.members.length - leads;
    if (reports < 4 || reports > 5) problems.push(`${t.key}: needs 4 or 5 reports, has ${reports}`);
    if (new Set(t.members.map((m) => m.slot)).size !== t.members.length) problems.push(`${t.key}: a slot repeats`);
    for (const m of t.members) if (!Array.isArray(m.focus)) problems.push(`${t.key}/${m.slot}: focus must be a list`);
    const members = t.members.map((m) => {
      const a = { ...m.avatar, id: `${t.key}-${m.slot}`, image: null };
      const title = lowerLabel(m.title);
      const pronoun = { woman: 'her', man: 'his' }[a.presentation] || 'their';
      a.prompt = `${ts.AVATAR_STYLE} Subject: ${articleFor(a.presentation)} ${a.presentation} in ${pronoun} ${a.apparentAge}, `
        + `of ${a.heritage} heritage. Hair: ${a.hair}. Clothing: ${a.attire}. Expression: ${a.expression}. `
        + `Role: works as ${articleFor(title)} ${title}.`;
      return { slot: m.slot, role: m.role, title: m.title, name: m.name,
        reportsTo: m.slot === 'lead' ? null : 'lead', focus: m.focus, avatar: a };
    });
    const entry = { key: t.key, kind: t.kind, rank: t.rank, label: t.label, blurb: t.blurb,
      purpose: t.purpose, caution: ts.TEAM_CAUTION, project: t.project, members };
    // Team text is what the Team screen shows (#4556, #4557), so it gets the same guard.
    if (emDashIn(entry)) problems.push(`${t.key}: em dash`);
    teams.push(entry);
  }
  const head = `'use strict';\n// ${NOTE}\n// Read it through engine/catalogue.js. The value below is strict JSON.\nmodule.exports = `;
  const files = {
    'catalogue-roles.js': head + JSON.stringify({ generated: NOTE, version: 1, groups, roles }, null, 2) + ';\n',
    'catalogue-teams.js': head + JSON.stringify({ generated: NOTE, version: 1, avatarStyle: ts.AVATAR_STYLE, teams }, null, 2) + ';\n',
  };
  return { files, problems };
}

/** The generated files that differ from what build() makes now (empty when current). */
function stale(outDir = OUT, src) {
  const { files } = build(src);
  return Object.keys(files).filter((n) => {
    const p = path.join(outDir, n);
    return !fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== files[n];
  });
}

function main(argv) {
  const { files, problems } = build();
  if (problems.length) {
    process.stderr.write('refused to write:\n  ' + problems.join('\n  ') + '\n');
    return 1;
  }
  if (argv.includes('--check')) {
    const s = stale();
    if (s.length) { process.stderr.write(`stale: ${s.join(', ')} (run node tools/catalogue/build.js)\n`); return 1; }
    process.stdout.write('ok: the generated files match their source\n');
    return 0;
  }
  for (const [n, text] of Object.entries(files)) fs.writeFileSync(path.join(OUT, n), text);
  const rs = require('./roles-source');
  const ts = require('./teams-source');
  const members = ts.teams.reduce((s, t) => s + t.members.length, 0);
  process.stdout.write(`wrote ${rs.roles.length} roles and ${ts.teams.length} teams (${members} members)\n`);
  return 0;
}

module.exports = { build, stale, EM_DASHES };
if (require.main === module) process.exitCode = main(process.argv.slice(2));
